# Dependencies
markdown: redcarpet
highlighter:      pygments
baseurl: /blog
exclude: ['README.md']

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pentest God | Blog
tagline:          'My Chronicles of Security Testing!'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Eshwar Getenv'
  url:            https://twitter.com/eshwargetenv

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pentestgod
